production:
  dialect: postgres
  datasource: user=postgres password=SdaJuLigpplDFtwVbVmAKAWocahCUkWO dbname=railway host=postgres.railway.internal port=5432 sslmode=disable
  dir: database/migrations
  table: migrations
